app:
  image: simplyhomework
  restart: always
  ports:
   - "80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/simplyhomework
   - MONGO_OPLOG_URL=mongodb://mongo/local
   - 'METEOR_SETTINGS={ "scholieren": { "client_id": "32c8014e0e49363bce563d940859dade", "client_pw": "a56c98c29403f35d7e6152caf12e5c5e" }, "public": { "analyticsSettings": { "Google Analytics" : { "trackingId": "UA-52373748-1" } } } }'
   - KADIRA_APP_ID=EkKhbLvn5zD6ksYep
   - KADIRA_APP_SECRET=ba8ab5e5-6562-4af3-9317-710317d3549c
   - ROOT_URL=http://app.simplyhomework.nl
   - MAIL_URL=smtp://lieuwerooijakkers@gmail.com:D_4mwX_LhMU4lkufwlEeLw@smtp.mandrillapp.com:587
   - DISABLE_WEBSOCKETS=true
   - VIRTUAL_HOST=app.simplyhomework.nl

web:
  image: homepage
  restart: always
  ports:
   - "80"
  environment:
   - 'VIRTUAL_HOST=*.simplyhomework.nl'

mongo:
  image: mongo:latest
  restart: always
  command: mongod --replSet meteor

proxy:
  image: jwilder/nginx-proxy
  restart: always
  environment:
   - DEFAULT_HOST=www.simplyhomework.nl
  ports:
   - "80:80"
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
